enum OriginEnum {
  FUI_VITIMA_DE_UMA_SITUACAO = 'FUI_VITIMA_DE_UMA_SITUACAO',
  TESTEMUNHEI_UMA_SITUACAO = 'TESTEMUNHEI_UMA_SITUACAO',
  COLETEI_UMA_SITUACAO_DO_NOTICIARIO = 'COLETEI_UMA_SITUACAO_DO_NOTICIARIO',
}

export default OriginEnum;
